### ISSUE TITLE
Changing Directory

### ISSUE THREAD

**Issue by bikewrecker** [martinvelez/cumulus#8]
I've noticed that the "cd" command doesn't seem to work properly. 

Say I'm working in the directory "/home/cumulus/HW1" and I want to move to the directory"/home/cumulus/HW2". If I've been working in the HW1 directory for a while, the CDE commands "cd .." or "cd ../HW2" don't seem to work. My CDE shell remains in the HW1 directory. 

I'm not sure exactly what you would need to do to reproduce this issue. Maybe just try changing directories via CDE shell after working on a project for a while. 

The workaround I've been using is to change directories on the left UI then close the CDE shell and reopen it.

**Comment by martinvelez** [comment]
Thank you for reporting this.  We cannot run `cd ../HW2`.  However, we are able to run `..` and then `cd HW2`.  

For the last few months, we have been working on an improved version of Cumulus called Kodethon ([www.kodethon.com](www.kodethon.com)).  The issue you reported is fixed in Kodethon.  

**I recommend that you migrate to Kodethon.**  The easiest way would be to do the following:

1. Zip up all of your files via the shell, e.g., `zip -r myfiles.zip *`
2. Log in to [Kodeton](www.kodethon.com).
3. Upload (or drag-n-drop) the zip file to your new Kodethon account.  It should automatically unzip.

Again, thank you for using Cumulus and even more for reporting the issue.  For Kodethon, we created forum that should make is easier for users to post questions and report issues: [Forum](http://www.kodethon.com/#/forum).
